version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: hamverilerin olduğu kaynak
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Satış tablosu
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: pdt_id
            description: Urun id'si
          - name: orders_id
            description: Siparis ID'si
          - name: date_date
            description: Satış tarihi
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id) "
          - dbt_utils.unique_combination_of_columns:
              arguments:
                combination_of_columns:
                  - orders_id
                  - pdt_id
      - name: product
        identifier: raw_gz_product
        description: ürün tablosu
        columns:
          - name: products_id
            description: Urun ID'si
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: nakliye tablosu
        columns:
          - name: orders_id
            description: Siparis ID'si
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
models:
  - name: int_campaigns
    description: tüm kaynaklardan gelen verilerin birleştirildiği ara model
    columns:
      - name: paid_source
        description: reklam kaynağı (adwords, bing, criteo, facebook)
        tests:
          - not_null
      - name: campaign_name
        description: kampanya adı
        tests:
          - not_null
  - name: int_campaigns_day
    description: int_campaigns modelinin her gün için toplu versiyonu
    columns:
      - name: date_date
        description: verinin ait olduğu tarih
        tests:
          - not_null
      - name: ads_cost
        description: günlük toplam reklam maliyeti
        tests:
          - not_null
      - name: ads_impressions
        description: günlük toplam gösterim
        tests:
          - not_null
      - name: ads_clicks
        description: günlük toplam tıklanma
        tests:
          - not_null
  - name: finance_campaigns_day
    description: global kpi
    columns:
      - name: ads_margin
        description: operational_margin - ads_cost
        tests:
          - not_null
      - name: average_basket
        description: her gün için ortalama sepet tutarı
        tests:
          - not_null

